### ISSUE TITLE
mod_rewrite is not default enabled

### ISSUE THREAD

**Issue by brtsos** [shopwareLabs/shopware-platform-vagrant#28]
mod_rewrite is not default enabled

**Comment by flohessling** [comment]
I will look into it, but it should be the case if ansible was executed properly:

`./ansible/roles/shopware-dev/tasks/main.yml`:

```
- name: enable mod_rewrite
  become: yes
  apache2_module:
    name: rewrite
    state: present
  notify: restart-apache
```
